spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - http://localhost:4200
              - http://host.docker.internal:4200
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - HEAD
      routes:
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservations/**
        - id: candidat-service
          uri: lb://candidat-service
          predicates:
            - Path=/candidats/**
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login-service/**
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/**
        - id: keycloak
          uri: lb://0.0.0.0:8080
          predicates:
            - Path=/auth/**
server:
  port: ${SERVER_PORT:9000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka/}
      
spring:
  profiles: abc-service-replica04
eureka:
  instance:
    appname: ABC-SERVICE
  client:    
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://register-service:8761/eureka    
server:
  port: 8004  
 
spring:
  profiles: abc-service-replica05
eureka:
  instance:
    appname: ABC-SERVICE
  client:    
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://register-service:8761/eureka    
server:
  port: 8005
